[package]
name = "gameboy-emulator"
version = "0.1.0"
edition = "2021"

[dependencies]
sdl2 = {version = "0.35.2", features = ["ttf"]}
serde = "1.0.147"
serde_json = "1.0.87"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

